name: Deploy to Production
on:
  workflow_dispatch:
jobs: 
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #default line
      - name: Say Hello World
        run: echo 'Hello, World'
